theme: minima
title: My information
author: davidhannnn
email: dhan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 This will contain my name, social media information,
 brag sheet and a picture of me.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
